development:
  adapter: postgresql
  database: imgblog_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: imgblog_test
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: imgblog_staging
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: imgblog_prod
  pool: 5
  timeout: 5000
